---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pb-api-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: petbattle-api.rules
    rules:
    - alert: PetBattleApiNotAvailable
      annotations:
        message: 'Pet Battle API in namespace {{ .Release.Namespace }} is not available for the last 1 minutes.'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle-api",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.prometheusrules.severity | default "critical" }}
    - alert: PetBattleMongoDBDiskUsage
      annotations:
        message: 'Pet Battle MongoDB disk usage in namespace {{ .Release.Namespace }} higher than 80%'
      expr: (kubelet_volume_stats_used_bytes{persistentvolumeclaim="pet-battle-api-mongodb",namespace="{{ .Release.Namespace }}"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="pet-battle-api-mongodb",namespace="{{ .Release.Namespace }}"}) * 100 > 80
      labels:
        severity: {{ .Values.prometheusrules.severity | default "warning" }}
    - alert: PetBattleApiMaxHttpRequestTime
      annotations:
        message: 'Pet Battle Api max http request time over last 5 min in namespace {{ .Release.Namespace }} exceeds 1.5 sec.'
      expr: max_over_time(http_server_requests_seconds_max{service="pet-battle-api",namespace="{{ .Release.Namespace }}"}[5m]) > 1.5
      labels:
        severity: {{ .Values.prometheusrules.severity | default "warning" }}
